#!/bin/bash

# Author : José Filipe Lopes Santos <filipesbim@yahoo.com.br>
# License: GPL3, http://www.gnu.org/copyleft/gpl.html
# Version: 1.0
# Date creation: 2012-02-06
# Last update: 2012-02-08

# Colors used in the output
declare -A COLORS
COLORS=(["red"]="\033[38;5;203m" ["green"]="\033[0;32m" ["blue"]="\033[38;5;111m" ["brown"]="\033[38;5;179m")

shift
action=$1
export="no"

if [ "$action" = "usage" ]; then
  echo "Durations of the done tasks:"
  echo "   duration usage"
  echo "      shows the mode of usage / help"
  echo "   duration OPTION [TERM...]"
  echo "      Duration of the done tasks by the specified terms"
  echo "      OPTIONS:"
  echo "         -o - shows the output"
  echo "         -e - export values to csv"
  echo ""
  exit  
  
elif [ "$action" = "-o" ]; then
    export="no"
    
elif [ "$action" = "-e" ]; then
    export="yes"
    
else

  echo "Option $action invalid !"
  echo "Durations of the done tasks:"
  echo "   duration usage"
  echo "      shows the mode of usage / help"
  echo "   duration OPTION [TERM...]"
  echo "      Duration of the done tasks by the specified terms"
  echo "      OPTIONS:"
  echo "         -o - shows the output"
  echo "         -e - export values to csv"
  echo ""
  exit  

fi
shift

terms=""
if [ "$#" > 0 ]; then
    terms=$@
fi

# Inicialization of the vars
dates_creation=()
due_dates=()
tasks=()
n=-1 # conter of the arrays
nfields=0 # counter of the fields by line
task=""
day=0
month=0
year=0
duration=""

# Split the info in the different fields
lines_done=$(grep "$terms" "$DONE_FILE")
for word in $lines_done
do
    if [ "$word" = "x" ]; then
	nfields=0
	task=""
	let n=$n+1

    elif [[ "$word" =~ [0-9]{2,4}-[0-9]{1,2}-[0-9]{1,2} ]]; then
	if [ "$nfields" = 1 ]; then
	    due_dates[$n]=$word
	elif [ "$nfields" = 2 ]; then
	    dates_creation[$n]=$word
	fi

    elif [[ "$word" =~ [a-zA-Z]\+ && "$nfields" = 3 ]]; then
	    task=$word
    else
	    task="$task $word"
    fi

    tasks[$n]=$task;
    let nfields=$nfields+1
done


if [ "$export" = "no" ]; then
    echo -e ${COLORS["red"]}" Calculate tasks durations \033[0m\n"
fi

# Calculate durations
for ((i=0;i<=$n;i++))
do

    if [ -z ${dates_creation[$i]} ]; then
    	continue;
    fi

    year=${dates_creation[$i]%%-*}
    r=${dates_creation[$i]#*-}
    month=${r%%-*}
    r=${r#*-}
    day=${r%%-*}
    date="$year-$month-$day"
    timestamp="$year$month$day"
    num_of_days=0
    duration=""
        
    if [ "$date" =  "${due_dates[$i]}" ]; then # somme date
        duration="1d"
    else
        while [ "$date" !=  "${due_dates[$i]}" ]
        do        
            # verify it is weekend
            week_day=$(date +%u -d $timestamp)  
            
            if [ "$week_day" -le 5 ]; then # day of week word (monday to friday)
                let num_of_days=$num_of_days+1
            fi            
            
            # Get the next day
            day=$(date +%d -d "$timestamp +1 day")
            month=$(date +%m -d "$timestamp +1 day") 
            year=$(date +%Y -d "$timestamp +1 day") 
            date="$year-$month-$day"
            timestamp="$year$month$day"
        done
        
        # verify it is weekend of the end day
        week_day=$(date +%u -d $timestamp)  
        
        if [ "$week_day" -le 5 ]; then # day of week word (monday to friday)
            let num_of_days=$num_of_days+1
        fi 
                
        # format duration
        if [ $num_of_days -le 30 ]; then
            duration=$num_of_days"d"
        elif [ $num_of_days -le 372 ]; then # less than one year
            let num_months=$num_of_days/31
            let rest_days=$num_of_days%31
            if [ $rest_days = 0 ]; then
                duration=$num_months"m"
            else
                duration=$rest_days"d "$num_months"m"
            fi
        else
            let num_years=$num_of_days/372
            let rest=$num_of_days%372
            let num_months=$rest/12
            let rest_days=$num_months%12
            
            if [ $rest = 0 ]; then
                duration=$num_years"y"
            elif [ $rest_days = 0 ]; then
                duration=$num_months"m "$num_years"y"
            else
                duration=$rest_days"d "$num_months"m "$num_years"y"
            fi
        fi                   
    fi

    if [ "$export" = "no" ]; then # output
        echo -ne ${COLORS["green"]} ${due_dates[$i]} "\033[0m"
        echo -ne ${COLORS["blue"]} ${dates_creation[$i]} "\033[0m"
        echo -ne ${COLORS["brown"]} $duration "\033[0m"
        echo -ne ${tasks[$i]}    
        echo ""
               
    elif [ "$export" = "yes" ]; then # export
        echo ${due_dates[$i]}";"${dates_creation[$i]}";"$duration";"${tasks[$i]}
    fi
done

